language: ruby
cache: bundler
rvm:
  - 2.1.4
services:
  - postgresql
  - redis
addons:
  postgresql: '9.3'
env:
  - RAILS_ENV=test
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - cp -f config/travis/database.yml config/database.yml
before_script:
  - bundle exec rake db:create db:migrate
script:
  - bundle exec teaspoon --server-timeout 500
  - bundle exec rspec spec
notifications:
  email:
    recipients:
    - t.bak@selleo.com
    format: html
